### PR TITLE
Visuals from EDA

### LINKED ISSUE #18: Exploratory Data Analysis
Building highly interactive charts

### PR DESCRIPTION
**Pull request by HydroPsalm**

### CODE REVIEW

**Comment by HydroPsalm** [comment]
I am yet to be perfect using git, kindly check if I have done the right thing. If not I can redo it if necessary

**Review by Johnne32 — APPROVED** [review]
Excellent visualizations. Good work👍

**Review by Osei365 — APPROVED** [review]
Very informative and articulate. Great job sir

**Comment by jideilori** [comment]
Run the notebook before saving so the charts and diagrams can show.

**Pull request merged**
