### PR TITLE
xgboost model  - private score - 1749266_50601

### PR DESCRIPTION
**Pull request by jideilori**
Please review

### CODE REVIEW

**Review by heisguyy — APPROVED** [review]

**Review by Osei365 — APPROVED** [review]
Great work sir

**Comment by Johnne32** [comment]
> Please review

Well done sir. Check your notebook score again because the last time I ran this notebook and submitted the result on Kaggle, I got 1741XXX on the private LB.

**Comment by heisguyy** [comment]
> Well done sir. Check your notebook score again because the last time I ran this notebook and submitted the result on Kaggle, I got 1741XXX on the private LB.

I sense different versions of libraries is the cause of this. Please check the params of the model on your side and screenshot it.

**Comment by Johnne32** [comment]
> I sense different versions of libraries is the cause of this. Please check the params of the model on your side and screenshot it.

The difference may most likely be as a result of different versions of libraries like you spotted out. I have taken screenshots so that it can be checked well.
Screenshot_2020-11-08 resturant_sales_xgb_1749266_50601 - Jupyter Notebook
Screenshot_2020-11-08 Restaurant Revenue Prediction Kaggle

**Pull request merged**
